<?php
// $Id: 

/**
 *  Implement hook_init().
 */

function portaltvsl_init() {
	global $base_url;
    $base = drupal_get_path('module', 'portaltvsl');	    
	$file = '/cortado/cortado-ovt-stripped-0.6.0.jar';
	define('PORTALTVSL_CORTADO_PATH', $base_url .'/'. $base .$file);
    drupal_add_css(drupal_get_path('module', 'portaltvsl') .'/portaltvsl.css');
}

/**
 * Implementation of hook_menu().
 *
 * @param $may_cache
 *   boolean indicating whether cacheable menu items should be returned
 *
 * @return
 *   array of menu information
 */

function portaltvsl_menu() {
  global $user;  
  $items = array();
  $items['embed/radiosl/%'] = array(
    'title' => 'Embed RadioSL',
    'page callback' => 'portaltvsl_radiosl_embed',
    'page arguments' => array(1),
	'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK);
  $items['embed/%node'] = array(
    'title' => 'Embed media',
    'page callback' => 'portaltvsl_embed',
    'page arguments' => array(1),
	'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK);
  return $items;
}

/**
 * Implementation of hook_block().
 */

function portaltvsl_block($op = 'list', $delta = 0, $edit = array()) {
  global $base_url;
  switch ($op) {
    case 'list':
	  $blocks[0] = array(
        'info' => t('RadioSL: radio station'),
      );	  
      return $blocks;
	break;
	
    case 'configure':
      switch ($delta) {
        case 0:
          $items = t('radiosl');
      }
      if (isset($items)) {
		if ($delta == 0){
      	  $form["portaltvsl_block_radiosl1_stream"] = array(
      		'#type' => 'textfield',
        	'#title' => t('Url stream', array('!items' => $items)),
			'#default_value' => variable_get('portaltvsl_block_radiosl1_stream', $base_url . ':8000/radiosl.ogg'),
    	  );
      	  return $form;	  
		}
	  }	
  	  break;
    case 'save':
      variable_set("portaltvsl_block_radiosl1_stream", $edit["portaltvsl_block_radiosl1_stream"]);
  	  break;
    
	case 'view':	  
	  switch($delta) {
	    case 0:
      	  $block = array(
          'content' => theme('portaltvsl_radiosl_block',1));
	    break;
  	  }																	
	  return $block;
	break;
  }
}

/**
 * Implementation of CCK's hook_field_formatter_info().
 */
function portaltvsl_field_formatter_info() {
  return array(
    'audio_player' => array(
      'label' => t('Audio player'),
      'field types' => array('filefield'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'description' => t('Displays all kinds of files with icon and audio player.'),
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function portaltvsl_theme() {
  return array(
    'portaltvsl_formatter_audio_player' => array(
      'arguments' => array('element' => NULL),
      'file' => 'portaltvsl_formatter.inc',
    ),
    'portaltvsl_file' => array(
      'arguments' => array('file' => NULL),
      'file' => 'portaltvsl_formatter.inc',
    ),
	'portaltvsl_player' => array(
      'arguments' => array('element' => NULL),
    ),
	'portaltvsl_embed' => array(
      'arguments' => array('element' => NULL, 'node' => NULL),
    ),
	'portaltvsl_player_embed_toolbar'	=> array(
      'arguments' => array('node' => NULL),
    ),
	'portaltvsl_radiosl_embed'	=> array(
      'arguments' => array('id' => NULL),
    ),
	'portaltvsl_radiosl_block'	=> array(
      'arguments' => array('id' => NULL),
    ),
  );
}

function theme_portaltvsl_player_embed_toolbar($element,$node) {
  global $base_path,$base_url;

  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/jquery.hoverIntent.minified.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/bgiframe_2.1.1/jquery.bgiframe.min.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/excanvas_r3/excanvas.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/jquery.bt.min.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/jquery.easing.1.3.js');

  $addtoany = _addtoany_create_button($node);
  $embed_str = '<iframe id="player-base" src="' . $base_url .'/embed/'. $node->nid . '" width="'.($element->width + 2).'" height="'.($element->height + 46).'" align="right" frameborder="0" scrolling="no"></iframe>';
  $embedPopup = '$(\'#player-embed a#embed\').bt(\'<textarea style="font-size:10px;height:60px;width:260px;border:0;" onFocus="this.select()">'.$embed_str.'</textarea>\',
  {
	positions: \'top\',
    trigger: \'click\',
	width: 260,
	centerPointX: .9,
	spikeLength: 15,
	spikeGirth: 40,
	padding: 15,
	cornerRadius: 25,
	fill: \'#FFF\',
	strokeStyle: \'#ABABAB\',
	strokeWidth: 1
  });';

  $help_content = '<div id="help-content" style="color: #000;font-size: 11px; font-family:Verdana,Tahoma,"DejaVu Sans",sans-serif;z-index: 999"><div style="float:left;">Compat&iacute;vel com Firefox 3.5+, Chrome 4.x+ e Opera 10.x+ usando HTML5 ou Internet Explorer utilizando plugin Java. <a href="'.$base_url .'/como-acessar" target="_new" style="color: #000;">Saiba Mais</a></div></div>';

  $helpPopup = '$(\'#player-embed a#help\').bt(\''.$help_content.'\',
  {
	positions: \'top\',
    trigger: \'click\',
	width: 260,
	centerPointX: .9,
	spikeLength: 15,
	spikeGirth: 40,
	padding: 15,
	cornerRadius: 25,
	fill: \'#FFF\',
	strokeStyle: \'#ABABAB\',
	strokeWidth: 1
  });';

  $r = '$(document).ready(function() { '.$embedPopup. $helpPopup .' })';
  drupal_add_js($r,'inline');
  $output = '
  <div id="player-embed" style="color:#FFFFFF;display:inline-block;font-size:12px;padding-left:3px;margin-top:0;text-align:left;vertical-align:bottom;width:30px;" >
  <a id="help" href="javascript:void(0);" style="color: #fff;"><img src="'.$base_path.'themes/tvsl/images/help_16_16.png" border="0">
  <a id="embed" href="javascript:void(0);" style="color: #fff;"><img src="'.$base_path.'themes/tvsl/images/embed_16_16.png" border="0"></a>'.$addtoany.'</div>';
  return $output;  
}

function theme_portaltvsl_player($element) {
  $output = '<video width="'.$element->width.'" height="'.$element->height.'" '.(($element->autoplay == 'true') ? 'autoplay' : '').' '.(($element->autobuffer == 'true') ? 'autobuffer' : '').' '.(($element->showcontrols == 'true') ? 'controls' : '') .' src="'.$element->mediafile.'" 
  poster="'.$element->poster.'" durationHint="'.$element->duration.'">
	<object id="portaltvsl-audio-player'.(($element->playerid) ? $element->playerid : '').'" width="'.$element->width.'" height="'.$element->height.'" codebase="http://java.sun.com/products/plugin/autodl/jinstall-1_4_2-windows-i586.cab#Version=1,4,2,0" classid="clsid:CAFEEFAC-0014-0002-0000-ABCDEFFEDCBA">
	  <param value="com.fluendo.player.Cortado.class" name="code"/>
	  <param value="'.PORTALTVSL_CORTADO_PATH.'" name="codebase"/>
	  <param value="'.PORTALTVSL_CORTADO_PATH.'" name="archive"/>
	  <param value="application/x-java-applet;jpi-version=1.4.2" name="type"/>
	  <param name="url" value="'.$element->mediafile.'">
	  <param name="BufferSize" value="4096">
	  <param name="BufferHigh" value="25">
	  <param name="BufferLow" value="5">
	  <param name="statusHeight" value="'.(($element->statusheight) ? $element->statusheight : 30).'">
	  <param name="autoPlay" value="'.(($element->autoplay == 'true') ? 'true' : 'false').'"/>
	  <comment>
		<applet id="portaltvsl-audio-player-applet'.(($element->playerid) ? $element->playerid : '').'" width="'.$element->width.'" height="'.$element->height.'" archive="'.PORTALTVSL_CORTADO_PATH.'" 
		  codebase="'.PORTALTVSL_CORTADO_PATH.'" code="com.fluendo.player.Cortado.class">
		  <param name="url" value="'.$element->mediafile.'"/>
		  <param name="BufferSize" value="4096"/>
		  <param name="BufferHigh" value="25"/>
		  <param name="BufferLow" value="5"/>
		  <param name="autoPlay" value="'.(($element->autoplay == 'true') ? 'true' : 'false').'"/>
		  <param name="statusHeight" value="(($element->statusheight) ? $element->statusheight : 30)">
	    </applet>
	  </comment>  
	</object>	
  </video>';
  return $output;
}

function theme_portaltvsl_radiosl_block($id) {
  global $base_path,$base_url;
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/jquery.hoverIntent.minified.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/bgiframe_2.1.1/jquery.bgiframe.min.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/excanvas_r3/excanvas.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/jquery.bt.min.js');
  drupal_add_js(drupal_get_path('module', 'portaltvsl') .'/popup/libs/jquery.easing.1.3.js');
  //drupal_add_css(drupal_get_path('module', 'portaltvsl') .'/portaltvsl-radiosl.css');
  $base = $base_url .'/'. drupal_get_path('module', 'portaltvsl');  
  $jquerybase = $base_url .'/'. drupal_get_path('module', 'jquery_update');
  $player_id = 'radiosl';
  $embed_str = '<iframe id="player-base" src="' . $base_url .'/embed/radiosl/1" style="width:256px;height:60px;text-align:right;" frameborder="0" scrolling="no"></iframe>';
  $b = '$(\'#player-embed a:first-child\').bt(\'<textarea style="font-size:10px;height:60px;width:260px;border:0;" onFocus="this.select()">'.$embed_str.'</textarea>\', 
  {
  positions: \'top\',
  trigger: \'click\',
  width: 260,
  centerPointX: .9,
  spikeLength: 65,
  spikeGirth: 40,
  padding: 15,
  cornerRadius: 25,
  fill: \'#FFF\',
  strokeStyle: \'#ABABAB\',
  strokeWidth: 1
  });';
  $r = '$(document).ready(function() { '.$b.' })';
  drupal_add_js($r,'inline');  
  $output = $embed_str;  
  $output .= '<div id="player-embed" style="width:30px;color:white;font-size:8px;color:#fff;float:left;margin:-60px -10px 30px 230px;position: absolute;">
  <a href="javascript:void(0);" style="color:#fff;">(+)</a></div>';  
  return $output;
}

function portaltvsl_radiosl_embed($id){
  $radiosl = theme('portaltvsl_radiosl_embed',$id);	
  print $radiosl;
}

function theme_portaltvsl_radiosl_embed($id) {
  global $base_url,$base_path,$language;
  
  $base = $base_url .'/'. drupal_get_path('module', 'portaltvsl');
  
  $jquerybase = $base_url .'/'. drupal_get_path('module', 'jquery_update');
  $player_id = 'radiosl';
  
  $stream = variable_get('portaltvsl_block_radiosl'.$id.'_stream', $base_url . ':8000/radiosl.ogg');
  
  $embed_str = '<iframe id="player-base" src="' . $base_url .'/embed/radiosl/1" width="250" height="60" align="right" frameborder="0" scrolling="no"></iframe>';
  $embedPopup = '$(\'#player-embed a:first-child\').bt(\'<textarea style="font-size:10px;height:60px;width:260px;border:0;" onFocus="this.select()">'.$embed_str.'</textarea>\', 
  {
  positions: \'right\',
  trigger: \'click\',
  width: 260,
  centerPointX: .9,
  spikeLength: 65,
  spikeGirth: 40,
  padding: 15,
  cornerRadius: 25,
  fill: \'#FFF\',
  strokeStyle: \'#ABABAB\',
  strokeWidth: 1
  });';

  $help_content = '<div id="help-content" style="color: #000;font-size: 11px; font-family:Verdana,Tahoma,"DejaVu Sans",sans-serif;z-index: 999"><div style="float:left;">Compat&iacute;vel com Firefox 3.5+., Chrome 4.x+ e Opera 10.x+ usando HTML5 ou Internet Explorer utilizando plugin Java. <a href="'.$base_url .'/como-acessar" target="_new" style="color: #000;">Saiba Mais</a></div></div>';
  $helpPopup = '$(\'a#help\').bt(\''.$help_content.'\', 
  {
  positions: \'bottom\',
  contentSelector: \'$("#help-content")\',
  trigger: \'click\',
  width: 210,
  centerPointX: 1,
  spikeLength: 0,
  spikeGirth: 0,
  padding: 2,
  cornerRadius: 0,
  fill: \'#FFF\',
  strokeStyle: \'#ABABAB\',
  strokeWidth: 1
  });';

  $r = '$(document).ready(function() { '.$embedPopup . $helpPopup .' })';

$output = '
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="'.$language->language.'" lang="'.$language->language.'" dir="'.$language->language.'">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    
<title>RádioSL | Portal MídiaSL</title>
<script type="text/javascript">
    var jBasePath = "'.$base.'/";
	var jBasePathLink = "'.$base_url .'/embed/radiosl/1";
    var jUrlStream = "'.$stream.'";	
	var backend = "java";
	var audioElementId = "'.$player_id.'";
</script>
<script type="text/javascript" src="'.$base.'/portaltvsl-radiosl.js"></script>
<script type="text/javascript" src="'.$jquerybase.'/replace/jquery.min.js?x"></script>
<script type="text/javascript" src="'.$base.'/popup/libs/jquery.hoverIntent.minified.js"></script>
<script type="text/javascript" src="'.$base.'/popup/libs/bgiframe_2.1.1/jquery.bgiframe.min.js"></script>
<script type="text/javascript" src="'.$base.'/popup/libs/excanvas_r3/excanvas.js"></script>
<script type="text/javascript" src="'.$base.'/popup/jquery.bt.min.js"></script>
<script type="text/javascript" src="'.$base.'/popup/libs/jquery.easing.1.3.js"></script>
<script type="text/javascript">'.$r.'</script>
<link type="text/css" rel="stylesheet" media="all" href="'.$base.'/portaltvsl-radiosl.css" />
</head>
<body>
<div id="radio-player"> 
<div class="logo"><img src="'.$base.'/images/logo-radio.png" border="0"/></div>
<div class="content">
<span id="info" style="white-space:nowrap;">(<span id="stt">loaded</span>)</span>
<span id="controls" style="white-space:nowrap;">
<a href="javascript:void(0)" onclick="javascript:volumeToggle();" title="mute"><img id="volumebutton" src="'.$base.'/images/volume-on.png" border="0" alt="mute"/></a>
<a href="javascript:void(0);" id="help" style="color:#fff;">ajuda</a>
<a href="javascript:void(0)" onclick="javascript:goPopUp();" title="detach"><img src="'.$base.'/images/popup.png" border="0" alt="detach" style="margin-top: -5px;"></a>
</span>
<span id="player-main">
<object id="'.$player_id.'IE" width="0" height="0" codebase="http://java.sun.com/products/plugin/autodl/jinstall-1_4_2-windows-i586.cab#Version=1,4,2,0" classid="clsid:CAFEEFAC-0014-0002-0000-ABCDEFFEDCBA">
  <param value="com.fluendo.player.Cortado.class" name="code"/>
  <param value="'.PORTALTVSL_CORTADO_PATH.'" name="codebase"/>
  <param value="'.PORTALTVSL_CORTADO_PATH.'" name="archive"/>
  <param value="application/x-java-applet;jpi-version=1.4.2" name="type"/>
  <param name="url" value="'.$stream.'">
  <param name="BufferSize" value="200">
  <param name="BufferHigh" value="25">
  <param name="BufferLow" value="5">
  <param name="autoPlay" value="false"/>
  <param value="false" name="local"/>
  <param name="video" value="true"/>
  <comment>
	<applet id="'.$player_id.'" width="0" height="0" archive="'.PORTALTVSL_CORTADO_PATH.'" 
	  codebase="'.PORTALTVSL_CORTADO_PATH.'" code="com.fluendo.player.Cortado.class">
	  <param name="url" value="'.$stream.'"/>
	  <param name="BufferSize" value="200"/>
	  <param name="BufferHigh" value="25"/>
	  <param name="BufferLow" value="5"/>
	  <param name="video" value="false"/>
	  <param name="autoPlay" value="false"/>
	  <param value="false" name="local"/>
	</applet>
  </comment>  
</object>
<audio id="'.$player_id.'H5" style="display: none;" src="'.$stream.'">
</audio>
</span>

<div id="play">
  <div style="display:block;float:left;">
	<a href="javascript:void(0)" onclick="javascript:doPlayStop();" title="play/stop"><img id="playerbutton" border="0" src="'.$base.'/images/b-play.png" alt="play"/></a>
  </div>
  <div id="displayArtist"></div>
  <div>&nbsp;<marquee id="displayTitle" SCROLLDELAY="230"><a href="'.$base_url.'" target="parent">Rádio Software Livre</a></marquee></div>
</div>
</div>
</body>
</html>';
return $output;
}

function portaltvsl_embed($node) {
  $output = '';   
  if (in_array($node->type,array('video','aovivo'))) { 
	global $base_url; 
	global $base_path;
	global $styles;
	if ($node->type == 'aovivo'){
	  $node->videox = $node->field_width[0]["value"];
	  $node->videoy = $node->field_height[0]["value"];
	  $width = $node->videox;
	  $height = $node->videoy;
	  $video_path = url($node->field_urlstream[0]["value"]);
	  $snapshot = $base_url . '/themes/tvsl/images/tvsl-banner-logo.png';
	  $autoplay = 'true';
	  $description = '<span style="font-size: 10px">' .$node->field_aovivo_status[0]["value"] .( ($node->field_aovivodatetime[0]["value"]) ? ' - '. $node->field_aovivodatetime[0]["value"] : '').'</span>';
	} else if ($node->type == 'video') {
	  $video_path = url($node->current_video_upload_file->filepath);
	  $width = '480';
	  $width = ($node->videox) ? $node->videox : $width;
	  $height = '360';
	  $height = ($node->videoy) ? $node->videoy : $height;		  
	  if ($node->iid) {
  		$imagenode = node_load($node->iid);
  		$snapshot = $base_url . '/' . $imagenode->images['snapshot'];
	  } else {
  		$snapshot = '';
	  }
	  $autoplay = 'false';
	  $description = '';
	} 
	$element = new stdClass();
    $element->width = $width;
	$element->height = $height;
	$element->poster = $snapshot;
	$element->mediafile =  $video_path;
	$element->showcontrols = true;
	$element->autoplay = "$autoplay";
	$element->statusheight = 30;
	$element->autobuffer = true;  	
	$output = theme('portaltvsl_embed',$element,$node);	
  }
  print $output;
}

function theme_portaltvsl_embed($element,$node){
	global $base_url,$language;	
	$videocontent = theme('portaltvsl_player',$element);	
  	$output = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="'.$language->language.'" lang="'.$language->language.'" dir="'.$language->language.'">
	<head>
	<title>embeded content</title>
	'.drupal_get_html_head().'
	'.drupal_get_css().'
	</head>
	<body class="embed">
	<div class="content">  
	<div id="video-media-embed" class="video-media-body">
	'.$videocontent.'
	</div>
	<a href="'.$base_url.'" target="new"><img src="'.$base_url.'/themes/tvsl/images/logo-embed.png" border="0"/></a>  
	<span id="video-label" style="width:'.$width.';font-size: 14px;font-weight: bold; vertical-align: top;line-height: 30px;">'.l($node->title,$node->path,array('target' => 'new')) .' '.$description.'</span>
	</div>
	</body>
	</html>';
	return $output;
}
