<?php



/*
function theme_video_player($node) {
  // include video.js file for Internet Explorer fixes
  //theme('video_get_script');
  drupal_add_js(drupal_get_path('module', 'video') . '/video.js');
  if (variable_get('video_playcounter', 1)) {
    db_query("UPDATE {video} SET play_counter = play_counter + 1 where vid = %d", $node->vid); //Increment play counter.
  }
  
  _video_scale_video($node);
  $output = module_invoke('video_'.$node->vtype, 'v_play', $node);
  
  return $output;
}
*/

/*
function video_menu() {
  global $user;  
  $items = array();

    if (arg(0) == 'node' && is_numeric(arg(1))) {
      if ($node = node_load(arg(1)) and $node->type == 'video') {

        //enable the download tab only if it is supported
        if (video_support_download($node)) {
          
          $menu_type = (variable_get('video_displaydownloadmenutab', 1)) ? MENU_LOCAL_TASK : MENU_CALLBACK;
          $items['node/'.$node->nid.'/download'] = array(
            'title' => 'Download',
            'page callback' => 'video_download',
            'page arguments' => array($node),
            'access arguments' => array('access video') && node_access('view', $node, $user->uid),
            'weight' => 5,
            'type' => $menu_type);
        }
      }
    }
  return $items;
}*/

/**
 * Displays a Drupal page containing recently added videos
 *
 * @return
 *   string HTML output
 */
function lumea_video_node() {
    theme('lumea_video_node', NULL);
}

/**
 * Displays a Drupal page containing recently added videos
 *
 * @return
 *   string HTML output
 */

function theme_lumea_video_node() {
  $output = '';
  return $output;
}

/**
 * Theme the teaser
 *
 * This is just in place for site admins and theme developers
 * who need to adjust how the teaser is themed.
 *
 * @param $node
 *   The node to be displayed.
 * @param $teaser
 *   Whether we are to generate a "teaser" or summary of the node, rather than display the whole thing.
 * @param $page
 *   Whether the node is being displayed as a standalone page. If this is TRUE, the node title should not be displayed, as it will be printed automatically by the theme system. Also, the module may choose to alter the default breadcrumb trail in this case.
 *
 * @return
 *   html
 */
function theme_lumea_video_teaser($node, $teaser = FALSE, $page = FALSE) {
  return $node->teaser;
}

